### ISSUE TITLE
Error Fix & New Feature Suggestion

### ISSUE THREAD

**Issue by joyhyunki** [YK-TIGER/word_memorize#1]
There's a problem in your flipCard function. The flashcard program is broken.
![image](https://github.com/user-attachments/assets/4db21094-8882-46b1-bbf8-7ff7019862b7)
![image](https://github.com/user-attachments/assets/ddd2fed9-a71d-4bdc-b288-4490cc4ed121)

**The wrong side is flipped. To fix this, please change your flipCard() function to below.**

function flipCard() {
    const flashcard = document.querySelector('.flashcard');
    flashcard.classList.toggle('flipped');
    const wordElement = document.getElementById('word');
    const definitionElement = document.getElementById('definition');
    // 내용 전환
    if (flashcard.classList.contains('flipped')) {
        // 플래시카드가 뒤집혔을 때
        wordElement.style.display = 'inline';
        definitionElement.style.display = 'none';
    } else {
        // 플래시카드가 앞면일 때
        definitionElement.style.display = 'inline';
        wordElement.style.display = 'none';
    }
}

Additionally, I spotted an error in the end of the code.

if (event.code === 'keyR') {
    let currentIndex = 0;
    updateCard();
}

**Here, the 'keyR' should be fixed to 'KeyR'.**

-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Additionally, I would like to request for a menu to choose whether to show definition or the words.
By the way, I do think this is a really good idea to study English words :)

- By Artyom42

**Comment by YK-TIGER** [comment]
코드짜고 branch 만들어서 pull request 해주세요 ㅠ

**Comment by YK-TIGER** [comment]
-bug fixed
